{% set name = "M2Crypto" %}
{% set version = "0.43.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name|lower }}-{{ version }}.tar.gz
  sha256: 6c2c1c7bb0e8aa768f7ca803da7dbc2666d4003b26bd7adf70233afc59d8cf33
  patches:
    - 0001-Fix-building-against-OpenSSL-in-non-standard-locatio.patch
    - 0002-Fix-setting-X509.verify_-variables.patch
    - 0003-Fix-use-of-ERR_reason_error_string.patch
    - 0004-Fix-double-free-from-bad-refactoring.patch
    - 0005-Fix-windows-by-dropping-OpenSSL-1.1-support.patch

build:
  number: 0
  script: # [not win]
    - sed -i.bak "/sys\/types.h/d" $PREFIX/include/openssl/e_os2.h  # [not win]
    - OPENSSL_PATH=$PREFIX {{ PYTHON }} -m pip install . -vv  # [not win]
    - mv $PREFIX/include/openssl/e_os2.h{.bak,}  # [not win]
  script:  # [win]
    - copy "%LIBRARY_PREFIX%\include\openssl\e_os2.h" "%LIBRARY_PREFIX%\include\openssl\e_os2.h.bak"  # [win]
    - for /F "usebackq tokens=*" %%i in (`findstr /v "sys/types.h" "%LIBRARY_PREFIX%\include\openssl\e_os2.h.bak"`) do @echo %%i > "%LIBRARY_PREFIX%\include\openssl\e_os2.h"  # [win]
    - set "OPENSSL_PATH=%LIBRARY_PREFIX%"  # [win]
    - {{ PYTHON }} -m pip install . -vv  # [win]
    - move /Y "%LIBRARY_PREFIX%\include\openssl\e_os2.h.bak" "%LIBRARY_PREFIX%\include\openssl\e_os2.h"  # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - swig                                   # [build_platform != target_platform]
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
  host:
    - openssl
    - pip
    - python
    - setuptools
    - swig >=2.0.4
  run:
    - openssl
    - python

test:
  imports:
    - M2Crypto
    - M2Crypto.SSL
  commands:
    - pip check
    - python -m pytest tests/ -v -rs -k "not test_ssl"
  requires:
    - parameterized
    - pip
    - pytest
  source_files:
    - tests

about:
  home: https://gitlab.com/m2crypto/m2crypto
  license: MIT
  license_file: LICENCE
  summary: 'M2Crypto: A Python crypto and SSL toolkit'

extra:
  recipe-maintainers:
    - chrisburr
