{% set name = "M2Crypto" %}
{% set version = "0.39.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 24c0f471358b8b19ad4c8aa9da12e868030b65c1fdb3279d006df60c9501338a
  patches:
    # set default_openssl path to conda prefix
    - openssl_default.patch
    # OpenSSL 3 patches (from fedora)
    - m2crypto-MR271-opensslversion.patch
    - m2crypto-0.38-ossl3-tests.patch
    - m2crypto-0.38-ossl3-tests-evp.patch
    # https://gitlab.com/m2crypto/m2crypto/-/issues/298
    - Remove-buggy-ifdef-statements-m2crypto-298.patch
    # Fix Windows issue in fedora's patches
    - Remove-OpenSSL-1.0.0-support-to-avoid-windows-issues.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - swig                                   # [build_platform != target_platform]
    - {{ compiler("c") }}
  host:
    - openssl
    - pip
    - python
    - setuptools
    - swig >=2.0.4
  run:
    - openssl
    - python

test:
  imports:
    - M2Crypto
    - M2Crypto.SSL
  commands:
    - pip check
    - python -m pytest tests/ -v -rs -k "not test_ssl"
  requires:
    - parameterized
    - pip
    - pytest
  source_files:
    - tests

about:
  home: https://gitlab.com/m2crypto/m2crypto
  license: MIT
  license_file: LICENCE
  summary: 'M2Crypto: A Python crypto and SSL toolkit'

extra:
  recipe-maintainers:
    - chrisburr
