{% set version = "0.31.0" %}

package:
  name: m2crypto
  version: {{ version }}

source:
  fn: M2Crypto-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/source/M/M2Crypto/M2Crypto-{{ version }}.tar.gz
  sha256: fd59a9705275d609948005f4cbcaf25f28a4271308237eb166169528692ce498

build:
  number: 0

requirements:
  host:
    - python
    - swig >=2.0.4
    - setuptools
    - openssl 1.0.*
  run:
    - python
    - typing  # [py<35]
    - openssl 1.0.*

test:
  imports:
    - M2Crypto
    - M2Crypto.SSL

about:
  home: https://gitlab.com/m2crypto/m2crypto
  license: MIT
  summary: 'M2Crypto: A Python crypto and SSL toolkit'

extra:
  recipe-maintainers:
    - danielfrg
