{% set name = "M2Crypto" %}
{% set version = "0.38.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 99f2260a30901c949a8dc6d5f82cd5312ffb8abc92e76633baf231bbbcb2decb
  patches:
    # set default_openssl path to conda prefix
    - openssl_default.patch

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler("c") }}
  host:
    - openssl
    - pip
    - python
    - setuptools
    - swig >=2.0.4
  run:
    - openssl
    - python

test:
  imports:
    - M2Crypto
    - M2Crypto.SSL
  commands:
    - pip check
    - python -m pytest tests/ -v -rs -k "not test_ssl"
  requires:
    - parameterized
    - pip
    - pytest
  source_files:
    - tests

about:
  home: https://gitlab.com/m2crypto/m2crypto
  license: MIT
  license_file: LICENCE
  summary: 'M2Crypto: A Python crypto and SSL toolkit'

extra:
  recipe-maintainers:
    - chrisburr
