{% set version = "0.24.0" %}

package:
  name: m2crypto
  version: {{ version }}

source:
  fn: M2Crypto-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/source/M/M2Crypto/M2Crypto-{{ version }}.tar.gz
  md5: 8e87235942c76d1ba9f999ee33764fdb

build:
  number: 1
  skip: True  # [py3k]
  preserve_egg_dir: yes

requirements:
  build:
    - python
    - setuptools
    - swig
    - openssl 1.0.*
  run:
    - python
    - distribute
    - openssl 1.0.*

test:
  imports:
    - M2Crypto
    - M2Crypto.SSL

about:
  home: https://github.com/martinpaljak/M2Crypto
  license: MIT License
  summary: 'M2Crypto: A Python crypto and SSL toolkit'

extra:
  recipe-maintainers:
    - danielfrg
