{% set version = "0.31.0" %}

package:
  name: m2crypto
  version: {{ version }}

source:
  fn: M2Crypto-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/source/M/M2Crypto/M2Crypto-{{ version }}.tar.gz
  sha256: fd59a9705275d609948005f4cbcaf25f28a4271308237eb166169528692ce498
  patches:
    - setup.py.patch  # [unix]

build:
  number: 1001

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
  host:
    - python
    - swig >=2.0.4
    - setuptools
    - openssl
  run:
    - python
    - typing  # [py<35]
    - openssl

test:
  imports:
    - M2Crypto
    - M2Crypto.SSL

about:
  home: https://gitlab.com/m2crypto/m2crypto
  license: MIT
  license_file: LICENCE
  summary: 'M2Crypto: A Python crypto and SSL toolkit'

extra:
  recipe-maintainers:
    - danielfrg
