{% set version = "0.33.0" %}

package:
  name: m2crypto
  version: {{ version }}

source:
  fn: M2Crypto-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/source/M/M2Crypto/M2Crypto-{{ version }}.tar.gz
  sha256: 75deaa3f6d25c8300c41da042a1abfa27154de5164c7073d68cb1809cedb8553
  patches:
    # don't search for extra include paths
    - setup.py.patch  # [unix]

build:
  number: 0

requirements:
  build:
    - {{ compiler("c") }}
  host:
    - python
    - swig >=2.0.4
    - setuptools
    - openssl
  run:
    - python
    - typing  # [py<35]
    - openssl

test:
  imports:
    - M2Crypto
    - M2Crypto.SSL

about:
  home: https://gitlab.com/m2crypto/m2crypto
  license: MIT
  license_file: LICENCE
  summary: 'M2Crypto: A Python crypto and SSL toolkit'

extra:
  recipe-maintainers:
    - danielfrg
