{% set version = "0.24.0" %}
{% set version_windows = "0.21.1" %}
{% set version_windows_pypi = "0.21.1-3" %}

package:
  name: m2crypto
  version: {{ version }}  # [not win]
  version: {{ version_windows }}  # [win]

source:
  fn: M2Crypto-{{ version }}.tar.gz  # [not win]
  url: https://pypi.python.org/packages/source/M/M2Crypto/M2Crypto-{{ version }}.tar.gz  # [not win]
  md5: 8e87235942c76d1ba9f999ee33764fdb  # [not win]
  fn: M2CryptoWin64-{{ version_windows_pypi }}.tar.gz  # [win]
  url: https://pypi.python.org/packages/source/M/M2CryptoWin64/M2CryptoWin64-{{ version_windows_pypi }}.tar.gz  # [win]
  sha1: A7C5AAF01D08CBB842972BC1E9547E5CF5E989BD  # [win]

build:
  number: 1
  skip: True  # [py3k]
  preserve_egg_dir: yes

requirements:
  build:
    - python
    - setuptools
    - swig
    - openssl 1.0.*
  run:
    - python
    - distribute
    - openssl 1.0.*

test:
  imports:
    - M2Crypto
    - M2Crypto.SSL

about:
  home: https://gitlab.com/m2crypto/m2crypto
  license: MIT License
  summary: 'M2Crypto: A Python crypto and SSL toolkit'

extra:
  recipe-maintainers:
    - danielfrg
