{% set version = "0.36.0" %}

package:
  name: m2crypto
  version: {{ version }}

source:
  url: https://pypi.python.org/packages/source/M/M2Crypto/M2Crypto-{{ version }}.tar.gz
  sha256: 1542c18e3ee5c01db5031d0b594677536963e3f54ecdf5315aeecb3a595b4dc1

build:
  number: 1

requirements:
  build:
    - {{ compiler("c") }}
  host:
    - python
    - swig >=2.0.4
    - setuptools
    - openssl
  run:
    - python
    - typing  # [py<35]
    - openssl

test:
  imports:
    - M2Crypto
    - M2Crypto.SSL

about:
  home: https://gitlab.com/m2crypto/m2crypto
  license: MIT
  license_file: LICENCE
  summary: 'M2Crypto: A Python crypto and SSL toolkit'

extra:
  recipe-maintainers:
    - danielfrg
