{% set version = "0.37.1" %}

package:
  name: m2crypto
  version: {{ version }}

source:
  url: https://pypi.python.org/packages/source/M/M2Crypto/M2Crypto-{{ version }}.tar.gz
  sha256: e4e42f068b78ccbf113e5d0a72ae5f480f6c3ace4940b91e4fff5598cfff6fb3

build:
  number: 1

requirements:
  build:
    - {{ compiler("c") }}
  host:
    - python
    - swig >=2.0.4
    - setuptools
    - openssl
  run:
    - python
    - typing  # [py<35]
    - openssl

test:
  imports:
    - M2Crypto
    - M2Crypto.SSL

about:
  home: https://gitlab.com/m2crypto/m2crypto
  license: MIT
  license_file: LICENCE
  summary: 'M2Crypto: A Python crypto and SSL toolkit'

extra:
  recipe-maintainers:
    - chrisburr
    - danielfrg
