{% set version = "0.36.0" %}

package:
  name: m2crypto
  version: {{ version }}

source:
  url: https://pypi.python.org/packages/source/M/M2Crypto/M2Crypto-{{ version }}.tar.gz
  sha256: 1542c18e3ee5c01db5031d0b594677536963e3f54ecdf5315aeecb3a595b4dc1

build:
  number: 0
  skip: true  # [aarch64 or ppc64le]
  script: '$PYTHON -m pip install --global-option="build_ext" --global-option="--openssl=$PREFIX" . -vv'

requirements:
  build:
    - {{ compiler("c") }}
  host:
    - python =2.7
    - pip
    - swig >=2.0.4
    - setuptools
    - openssl =1.0
  run:
    - python =2.7
    - typing
    - openssl

test:
  imports:
    - M2Crypto
    - M2Crypto.SSL

about:
  home: https://gitlab.com/m2crypto/m2crypto
  license: MIT
  license_file: LICENCE
  summary: 'M2Crypto: A Python crypto and SSL toolkit'

extra:
  recipe-maintainers:
    - chrisburr
    - danielfrg
