{% set version = "0.30.1" %}

package:
  name: m2crypto
  version: {{ version }}

source:
  fn: M2Crypto-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/source/M/M2Crypto/M2Crypto-{{ version }}.tar.gz
  sha256: a1b2751cdadc6afac3df8a5799676b7b7c67a6ad144bb62d38563062e7cd3fc6

build:
  number: 1

requirements:
  host:
    - python
    - swig >=2.0.4
    - setuptools
    - openssl 1.0.*
  run:
    - python
    - typing  # [py<35]
    - openssl 1.0.*

test:
  imports:
    - M2Crypto
    - M2Crypto.SSL

about:
  home: https://gitlab.com/m2crypto/m2crypto
  license: MIT
  summary: 'M2Crypto: A Python crypto and SSL toolkit'

extra:
  recipe-maintainers:
    - danielfrg
