travis:
  secure:
    BINSTAR_TOKEN: mwKaQ7L5sh6/qOCdyfiugfid0W0WjH4yEX6HQlme2pfpwc0hhZrz69cIPowvdnAWkNO+sScRI1YxPYm+6MVdqG8tJ+PcBAtP36R4rLW1RiPA3LW5L+EoO0B7Ho3DiEyUE9JdA0TySWRVjUCI93MZ6gCXtOb7luX+z07gPIEdoKpvG8+fEcpXgk/55PyjP1U5J2KdpiJbkQscKW+Obyq68C5oEMVTF6jA5rzu6ZJbiVMmoSr1GC4llewxkYlZkzZEk3iMWWwnnYlcnfimNP/o3yzwzjb4/tUhjg9FQoDPb8Jpw5zYuQYjfmikrgemRVm9B7di1+35wjdBrtjIrcHOTnW0F6lSHyGY+Jy2rB4HD7h/7ncUmR5Pdf8ppSB4MOtoPfOgqyfX9dA35nPYSwWWYwtr5FbGii19YiQJg/a3pX+Db2yEKfNgMYRJQC+vDpyUJBQIm+GJULrz0IgPwFdcnsSD+9IDVDb/p/mGwGCWVZ88RYMdvbjXeb5Eg+EevzmQ5WB+LZ3YZXnWlmRjHJQWHFYkw2yrDKtgI5A3+CPUrR5ECFZEddeZaByvBWzZcDFHiSGnxcJiugdPznaGfRcM9T3PUKh13JFk7UYCq1fw38QE9H66YpG0zq+bq6aZg6BfhmgPzWaU7AW5jc41Y20hyZTjlVmnJKf+SEfUrmixlIQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
